name: publish docker image

on:
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
      - 'kubelet/**'
  workflow_dispatch:

jobs:
  push:
    name: push docker image to the artifact registry
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: bulid the image
        run: |
          docker build -f kubelet/Dockerfile -t kubelet:latest .

      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push the image
        run: |
          IMAGE_ID=ghcr.io/plakarkorp/kubelet
          SHORT_SHA=$(echo "${{github.sha}}" | cut -c1-8)
          VERSION="$SHORT_SHA-$(date +%Y%m%d%H%M)"
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag kubelet $IMAGE_ID:$VERSION
          docker tag kubelet $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
